### ISSUE TITLE
Building on Windows with mingw_64

### ISSUE THREAD

**Issue by jlmelville** [eddelbuettel/rcppannoy#27]
I tried building this (immensely helpful and educational) package on Windows 10 with RStudio via `devtools::load_all(".")` and building with the `g++` that comes with `Rtools\mingw_64` fails. It doesn't realize it's on Windows, and wants to `#include <sys/mman.h>`.

Both the 32-bit and 64-bit versions of MinGW have a `__MINGW32__` macro, so changing the check on line 37 of `annoylib.h` worked for me:

```C++
#if defined(_MSC_VER) || defined(__MINGW32__)
#ifdef _MSC_VER
#define NOMINMAX
#endif
#include "mman.h"
#include <windows.h>
#else
#include <sys/mman.h>
#endif
```

**Comment by eddelbuettel** [comment]
Hm, but it [build fine on Windows as it does everywhere else](https://cloud.r-project.org/web/checks/check_results_RcppAnnoy.html).

Plus, that is a line in the upstream code.

**Comment by eddelbuettel** [comment]
And it is still [unchanged upstream](https://github.com/spotify/annoy/blob/master/src/annoylib.h#L37-L43) so it seems like you should make sure `load_all()` does not unset `_MSER_VER` which it may.  Not our fault.

Also, try to communicate with `diff` output, not new code chunk as that makes the change more apparent.
