### ISSUE TITLE
Strange behavior

### ISSUE THREAD

**Issue by pommedeterresautee** [eddelbuettel/rcppannoy#3]
I have trained a model with RCPPAnnoy and I don t think the behavior makes sense
```
> a$getNNsByItem(12000, 2)
[1] 12000  8672
> a$getNNsByItem(12000, 10)
 [1] 12000 13752 15723  5171 13957 15702  1819 16020 13101 15279
```

Two things are not correct: the document 12 000 is in the request AND in the response.
The document 8672 is selected when I ask for the two closest, but but is not in the 10th closest.

Is it normal?

Kind regards,
Michael

**Comment by erikbern** [comment]
This is correct behavior. The A in Annoy stands for "approximate" which means you might not find the top 2 if you request the top 2.

And yes the query point is returned in the results, generally as the first item. This is maybe a bit more arguable but I didn't see a reason to explicitly remove it

**Comment by pommedeterresautee** [comment]
Thanks
