### ISSUE TITLE
Fix vignette description of output distance vector

### ISSUE THREAD

**Issue by LTLA** [eddelbuettel/rcppannoy#31]
Note to self: the specification of the output distance vector in the vignette is wrong, it should be `std::vector<ANNOYTYPE>` rather than a vector of `double`s. I wonder if there is a way to extract out the C++ blocks from the vignette and compile them in some way, to make sure the advice is correct?

**Comment by eddelbuettel** [comment]
Hm, I just tried `knitr::purl()` and it failed returning an essentially empty file.  

Looking more closely I see that your code chunks are just `pandoc` chunks for hightlighting (a mode I use myself all the time too).  Short of cooking up a simple regexp expression, you can _probably_ ask pandoc to extract these.  But you'd have to look at how.

**Comment by LTLA** [comment]
Here's a script that will compile the C++ code in the vignette:

```r
# Identify all 'cpp' code chunks.
X <- readLines("rcppannoy.Rmd")
starts <- grep("^```cpp$", X)
ends <- grep("^```$", X)

I <- findInterval(ends, starts)
keep <- !duplicated(I) & I>0L

code.I <- mapply(seq, from=starts+1L, to=ends[keep]-1L)
code.chunks <- X[unlist(code.I)]

# Add preprocessor statements, variables necessary for compilation.
end.pp <- grep("MyAnnoyIndex;$", code.chunks)
total <- c(
    head(code.chunks, end.pp),
    "#include <vector>",
    "#include <algorithm>",
    "// [[Rcpp::depends(RcppAnnoy)]]",
    "// [[Rcpp::export]]", 
    "Rcpp::IntegerVector testfun(Rcpp::NumericMatrix mat) {",
    "int c=0, K=5;",
    "std::vector<ANNOYTYPE> stub(mat.ncol());",
    "ANNOYTYPE* query=stub.data();",
    tail(code.chunks, -end.pp),
    "return Rcpp::IntegerVector(neighbor_index.begin(), neighbor_index.end());",
    "}"
)   

# Compile and execute as a test.
total <- paste(total, collapse="\n")
library(Rcpp)
out <- sourceCpp(code=total)
testfun(matrix(0, 10, 5))
```

**Comment by eddelbuettel** [comment]
Nice one!

**Comment by LTLA** [comment]
In fact, I wonder whether it would be worth putting this into the package as an official unit test. This would check that the vignette's advice is correct across versions and across all CRAN systems.

**Comment by eddelbuettel** [comment]
You could of course just write it as a vignette too :)

````
```{Rcpp chunkone otheroption}
...
```
````

That said, I _like_ the script and I also like the 'pandoc' mode of the vignette.

**Comment by LTLA** [comment]
Wow, I didn't realize knitr had a Rcpp engine. This is pretty neat, see #33.
