### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by pommedeterresautee** [eddelbuettel/rcppannoy#4]
Is it normal that the documentation appearing in this file (https://github.com/eddelbuettel/rcppannoy/blob/master/src/annoy.cpp#L95) appear nowhere in the compiled package?

It is not very easy to use in real situation as RStudio (beta version) doesn't guess the list of possible functions when I enter the $ after the main object name.

Is there a way to fix the two discoverability issues?

Kind regards,
Michael

**Comment by eddelbuettel** [comment]
This is related to Rcpp Modules, and I invite you to tead up on in eg via the Rcpp Modules vignettes,
