### ISSUE TITLE
Expose `set_seed` method

### ISSUE THREAD

**Issue by jlmelville** [eddelbuettel/rcppannoy#40]
The underlying C++ classes (and the Python wrapper) expose a `set_seed` method which seeds the internal `KissRandom` rng. Could it be added to RcppAnnoy?

I have an issue where if an Annoy index gets written to disk and is larger than 2GB in size, Annoy is unable to read it back in (at least on my machine, the `off_t` type used internally by Annoy is 32-bit). A possible work-around would be to contruct multiple smaller indexes, and then merge the results. But this only works if the seed can be altered for each build.

I would be happy to work on a pr for this if there is a chance of it being accepted.

**Comment by eddelbuettel** [comment]
Yes, could do if we do it carefully.   For R extensions we often prefer to use R's RNGs to be reproducible which is why I had not gone there yet -- for (Rcpp)Annoy it is arguably as important to play nice with the Python (and other languages) behaviour.  

The code is a wee bit byzantine as we use Rcpp Modules in a templated fashion--let me know if you get lost.  Sending a single scalar down should be pretty straightforward.

**Comment by eddelbuettel** [comment]
I just had ten minutes and a cup of tea at hand -- can you check the [branch](https://github.com/eddelbuettel/rcppannoy/tree/feature/set_seed) I just pushed?

I will probably make it a PR in due course.

**Comment by jlmelville** [comment]
Thanks for looking into it with such alacrity. Looks good to me. I made the same changes to `annoy.cpp` (but was not quick enough to submit the PR), and I am getting different results with different seeds, so it's working. 

There's a [test/seed_test.py](https://github.com/spotify/annoy/blob/master/test/seed_test.py) in Annoy, but it doesn't do much except test that keeping the seed the same doesn't affect the results.

Other than that, I was thinking of modifying the vignette to note that the seed can be modified. I can make that a separate PR if desired.

**Comment by eddelbuettel** [comment]
Sounds good on all fronts. Will merge now -- thanks for checking -- and had pondered a unit test too. Validating that two two different seeds yield different vectors seems good enough.  Ditto with a brief mention in the vignette, so sync with what the repo will look like in a second and ship a follow-up PR.
