### ISSUE TITLE
Not able to save a model

### ISSUE THREAD

**Issue by pommedeterresautee** [eddelbuettel/rcppannoy#5]
I am under Windows, and I noticed that when I train a model based on > 10K objets, I can t save it. Not tried on Linux.

After training, the model seems to work correctly (seems -> see other posted issue) but as soon as I call save it is finished, I can t request anything. Then I unload, restart R... try to recreate an object with the same size and reload the saved model. When I request anything I get this error message:
```
> a$getNNsByItem(18841, 5)
Error: vector::_M_range_insert
```

Any idea?

Kind regards,
Michael

**Comment by eddelbuettel** [comment]
Not reproducible.

**Comment by eddelbuettel** [comment]
I'll close this inactive tread.
