### ISSUE TITLE
rcppannoy loading/installation error

### ISSUE THREAD

**Issue by tshicelg** [eddelbuettel/rcppannoy#54]
Hi

I got this error when installing RcppAnnoy.  This actually happened when I was trying to load Suerat package, got this error which led me to RcppAnnoy.  I uninstalled it and now try to install it but failed.

Thanks!

> install.packages("RcppAnnoy")
Installing package into ‘/home/rstudio/R/R_3.6’
(as ‘lib’ is unspecified)
trying URL 'https://mran.microsoft.com/snapshot/2019-11-11/src/contrib/RcppAnnoy_0.0.13.tar.gz'
Content type 'application/octet-stream' length 439735 bytes (429 KB)
==================================================
downloaded 429 KB

* installing *source* package ‘RcppAnnoy’ ...
** package ‘RcppAnnoy’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
g++ -std=gnu++11 -I"/usr/local/lib/R/include" -DNDEBUG -I../inst/include/ -I"/home/rstudio/R/R_3.6/Rcpp/include" -I/usr/local/include  -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c annoy.cpp -o annoy.o
gcc -I"/usr/local/lib/R/include" -DNDEBUG -I../inst/include/ -I"/home/rstudio/R/R_3.6/Rcpp/include" -I/usr/local/include  -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c init.c -o init.o
g++ -std=gnu++11 -shared -L/usr/local/lib/R/lib -L/usr/local/lib -o RcppAnnoy.so annoy.o init.o -L/usr/local/lib/R/lib -lR
installing to /home/rstudio/R/R_3.6/00LOCK-RcppAnnoy/00new/RcppAnnoy/libs
** R
** demo
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘RcppAnnoy’ in .doLoadActions(where, attach):
 error in load action .__A__.1 for package RcppAnnoy: loadModule(module = "AnnoyAngular", what = TRUE, env = ns, loadNow = TRUE): Unable to load module "AnnoyAngular": cannot allocate vector of size 701930.9 Gb
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/home/rstudio/R/R_3.6/RcppAnnoy’
Warning in install.packages :
  installation of package ‘RcppAnnoy’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/Rtmpi97ovS/downloaded_packages’

> sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 9 (stretch)

Matrix products: default
BLAS/LAPACK: /usr/lib/libopenblasp-r0.2.19.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=C              LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.6.1 tools_3.6.1

**Comment by tshicelg** [comment]
OK.  Found a solution.  I've tried multiple times just installing RcppAnnoy (also tried the latest version 0.0.14).  All failed.  However, after I also removed Rcpp package and re-installed both, it worked.

**Comment by eddelbuettel** [comment]
Yes, that can happen, and they need to match.  No way to tell _ex ante_ because the system does not 'write down' what compiler was used for dependencies.

**Comment by tshicelg** [comment]
Thanks!  A lesson learned.

**Comment by eddelbuettel** [comment]
A minor "tax" of using C++.  Does not happen this way with C. But on plus side all other Rcpp-using packages will be fine now too ;-)

**Comment by tshicelg** [comment]
Good to know.  Thanks!

**Comment by gangcai** [comment]
Errors gone after changing CXX11 = g++ in  R-4.0.3/lib64/R/etc/Makeconf  to CXX11 = gcc
