### ISSUE TITLE
Version 0.0.15 broke BiocNeighbors

### ISSUE THREAD

**Issue by lcolladotor** [eddelbuettel/rcppannoy#57]
Hi,

I'm unfamiliar with `RcppAnnoy` but I just ran into an issue where the changes from 0.0.14 to 0.0.15 broke the reverse dependency `BiocNeighbors` as I described in detailed to @LTLA
 at https://github.com/LTLA/BiocNeighbors/issues/10. I'm letting you know as it could involve a fix either on the `BiocNeighbors` side or the `RcppAnnoy` one (I just don't know).

I noticed this while trying to update https://jhubiostatistics.shinyapps.io/spatialLIBD/. 

Best,
Leo

**Comment by eddelbuettel** [comment]
Thanks for the heads, I am sure @LTLA and I should be able to sort it out.

**Comment by eddelbuettel** [comment]
(This is now taken care of in master thanks to very nice flurry of activity by @erikbern @jlmelville @LTLA and myself.  We should have 0.0.16 on CRAN by end of week; I will close it then.  If anybody needs a tarball of 0.0.15.2 in a [drat](https://github.com/eddelbuettel/drat)-able repo let me know, else just fetch master.)

**Comment by lcolladotor** [comment]
Awesome, thanks for all the work and the updates! I'll keep an eye for 0.0.16 as that's what's stopping https://github.com/Bioconductor/Contributions/issues/1389#issuecomment-594074136 (I don't think that I can use another `RcppAnnoy` version in Bioconductor's Single Package Builder infrastructure besides the latest from CRAN).

Best,
Leo

**Comment by eddelbuettel** [comment]
If you need a new version NOW (ie today) I can roll one up into a drat you can call via Suggests: and Additional_Repositiries.  

Otherwise by end of week / weekend / Monday at the latest a new 0.0.16 will on CRAN, and it will be *awesome*.

**Comment by LTLA** [comment]
@lcolladotor I don't understand. BiocNeighbors is all green on BioC-release and Bioc-devel.

**Comment by lcolladotor** [comment]
Ohh, ok! Thanks to the both of you! 

I dropped all the code related to `RcppAnnoy`'s versions at https://github.com/LieberInstitute/spatialLIBD/commit/5024450a66d36e253d898dbf180757a510bdc219 and it all works again (both on Travis and BioC's SBP). I didn't realize earlier that I didn't need to wait for 0.0.16. Thanks!!

* Travis: https://travis-ci.com/LieberInstitute/spatialLIBD/builds/151599703?utm_source=slack&utm_medium=notification
* Bioc: http://bioconductor.org/spb_reports/spatialLIBD_buildreport_20200303135350.html (shows other warnings, nothing to do with `RcppAnnoy`)

Best,
Leo

**Comment by eddelbuettel** [comment]
This is also fixed in 0.0.16 now on CRAN.
