### ISSUE TITLE
Complete the documentation

### ISSUE THREAD

**Issue by pommedeterresautee** [eddelbuettel/rcppannoy#6]
There is an important parameter being never documented, it is the number to give to build function. It is just said on Annoy deposit that it should be related to our data. What is the meaning of the parameter? Is more better? Is there some rule to follow? Is is an issue to put something to high or to low?

Kind regards,
Michael

**Comment by eddelbuettel** [comment]
I have no idea what you are asking.

**Comment by erikbern** [comment]
the number of trees?

**Comment by pommedeterresautee** [comment]
Yeah number of trees.

**Comment by eddelbuettel** [comment]
Can you write a patch, or as they call it around here, prepare a pull request?

**Comment by eddelbuettel** [comment]
I'll close this inactive thread.
