### ISSUE TITLE
Unable to Save

### ISSUE THREAD

**Issue by chulmelowe** [eddelbuettel/rcppannoy#69]
I've fit a model on a very large (330K+ items, each with 350 elements) data set and while the model works fine, I don't seem to be able to save it out. I don't get an error message when I save, it just seems to keep running indefinitely. From what I can tell, the CPU is the bottle neck. Do you have any recommendations for overcoming this issue?

I'm running R version 3.6.2 on Windows 2012 Server with 16 available processors.

**Comment by eddelbuettel** [comment]
Hm, sorry to hear that.  I do not think we do anything special and just 'hand that off' to the underlying API.  

Could you possibly try to create a (much smaller) [minimally complete verifiable example](https://stackoverflow.com/help/minimal-reproducible-example) ?

**Comment by chulmelowe** [comment]
Actually, it worked this morning without the save operation hanging up. I'm really not sure why it didn't work yesterday but did today, it's not as if anything changed overnight. Thank you for your time.

**Comment by eddelbuettel** [comment]
The Windows file system has been known to have the odd "surprises" for users :)   Glad it's sorted out as this operation _should be_ just a a very plain dump of a (possibly large) vector to disk.
