### ISSUE TITLE
Pass the whole matrix to addItem and getNNs function

### ISSUE THREAD

**Issue by yzizhen** [eddelbuettel/rcppannoy#70]
For big matrix, it is too slow to add each row using addItem function, and too slow to call getNNsbyVector function row by row for big query matrix. Could you add new functions to allow passing the whole matrix as input for building the tree and for query?
Thanks a lot!

**Comment by LTLA** [comment]
FWIW the `BiocNeighbors::findAnnoy` interface and related functions operate on whole matrices.

**Comment by eddelbuettel** [comment]
Hi @yzizhen that seems like a reasonable suggesion, on the other hand we always ways followed the Python API of `annoy` itself pretty closely which AFAIK does not have that.   And @LTLA is of course spot: maybe his BioConductor package can help you?

**Comment by yzizhen** [comment]
Hi, Dirk

Thanks for the quick response. I would expect looping across all the rows
would be a lot faster in C++ than in R, when users have a matrix with
millions of rows to process.  It might be less of a problem for python.
Having these new functionalities could really help adaptation of this
package in R community for computationally heavy tasks.

Thanks a lot
Zizhen

**Comment by eddelbuettel** [comment]
Please feel free to propose such an addition in pull request.  As @LTLA mentioned you may also want to look at the `BiocNeighbors` package.

**Comment by yzizhen** [comment]
Thanks a lot for the suggestion. I found exactly what I need in
BiocNeighbors package.

Best
Zizhen

**Comment by yzizhen** [comment]
Just one more thing, could you add Cosine function to the BiocNeighbors
package as well? Only Euclidean and Manhattan distance metrics are
supported now.

Thanks
