### ISSUE TITLE
Compilation error caused by lack of compiler

### ISSUE THREAD

**Issue by regiopires** [eddelbuettel/rcppannoy#77]
```
Selection: 1
trying URL 'https://cloud.r-project.org/src/contrib/RcppAnnoy_0.0.22.tar.gz'
Content type 'application/x-gzip' length 156284 bytes (152 KB)
==================================================
downloaded 152 KB

* installing *source* package ‘RcppAnnoy’ ...
** package ‘RcppAnnoy’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
g++-7 -std=gnu++17 -fPIC -std=gnu++17 -I"/scratch/unifesp/pgt/gustavo.kajitani/conda-env/meu_env/lib/R/include" -DNDEBUG -I../inst/include/  -I"/scratch/unifesp/pgt/gustavo.kajitani/conda-env/meu_env/lib/R/library/Rcpp/include" -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /scratch/unifesp/pgt/gustavo.kajitani/conda-env/meu_env/include -I/scratch/unifesp/pgt/gustavo.kajitani/conda-env/meu_env/include -Wl,-rpath-link,/scratch/unifesp/pgt/gustavo.kajitani/conda-env/meu_env/lib  -fpic  -fvisibility-inlines-hidden  -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /scratch/unifesp/pgt/gustavo.kajitani/conda-env/meu_env/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/r-base_1621283253293/work=/usr/local/src/conda/r-base-3.6.3 -fdebug-prefix-map=/scratch/unifesp/pgt/gustavo.kajitani/conda-env/meu_env=/usr/local/src/conda-prefix  -c RcppExports.cpp -o RcppExports.o
/bin/sh: g++-7: command not found
make: *** [/scratch/unifesp/pgt/gustavo.kajitani/conda-env/meu_env/lib/R/etc/Makeconf:176: RcppExports.o] Error 127
ERROR: compilation failed for package ‘RcppAnnoy’
* removing ‘/scratch/unifesp/pgt/gustavo.kajitani/conda-env/meu_env/lib/R/library/RcppAnnoy’

The downloaded source packages are in
	‘/tmp/RtmpoCkC5X/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning message:
In install.packages("RcppAnnoy") :
  installation of package ‘RcppAnnoy’ had non-zero exit status
> 
```

**Comment by eddelbuettel** [comment]
You need a compiler:

```
/bin/sh: g++-7: command not found
```

I should note that you also need a _recent-enough_ compiler.  You may want to get in touch with the admins of your local machine.

**Comment by regiopires** [comment]
I use gcc 9.3 but I also have versions 11.1, 10.2 and 13.2 configured. Which I load as needed using the module. But they all fail with the same error.

**Comment by regiopires** [comment]
$ g++ --version
g++ (GCC) 13.2.0
Copyright (C) 2023 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ g++-7 -std=gnu++17 -fPIC -std=gnu++17 -I"/scratch/unifesp/pgt/softwares/app/R/4.4.0/lib64/R/include" -DNDEBUG -I../inst/include -DTOML_ENABLE_FLOAT16=0 -I'/scratch/unifesp/pgt/softwares/app/R/4.4.0/lib64/R/library/Rcpp/include' -I/scratch/app/pcre2/10.37/include -I/scratch/app/gcc/9.3/include    -fpic  -g -O2   -c RcppExports.cpp -o RcppExports.o
-bash: g++-7: comando não encontrado

**Comment by eddelbuettel** [comment]
You need to configure this _at the R level_ for example via file `~/.R/Makevars`.  For me it says

```
$ R CMD config CC
ccache gcc
$ R CMD config CXX
ccache g++
$ R CMD config CXX17
ccache g++
$ 
```

because I also [like to use `ccache`](https://dirk.eddelbuettel.com/blog/2017/11/27/) but that is immaterial here.  

You problem is that R was built with g++-7 and expects it but you are doing something _on your system_ that makes that go sideways.  You will need to sort that out locally I am afraid.

**Comment by eddelbuettel** [comment]
So basically trying running this command in the shell `R CMD config CXX` (and/or `R CMD config CXX17`) and then see if you can also run the command displayed by R, for example by appenung `--version`.  

In my case above `gcc --version` and `g++ --version` both work as they are my default system compilers, as well the settings R was built with and hence the ones it expects to be available to build packages.
